### ISSUE TITLE
libwemd.so not found

### ISSUE THREAD

**Issue by LutaoChu** [ThierryDeruyttere/Talk2Car-Destination#4]
Run bash test.sh   under baselines/PDPC ，encounter the following error
```   
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    from model import PDPC
  File "Talk2Car-Destination/baselines/PDPC/model.py", line 15, in <module>
    import mmfp_utils
  File "Talk2Car-Destination/baselines/PDPC/mmfp_utils.py", line 3, in <module>
    from wemd import computeWEMD
  File "Talk2Car-Destination/baselines/PDPC/wemd.py", line 5, in <module>
    lib = ctypes.cdll.LoadLibrary("../wemd/lib/libwemd.so")
  File "/home/lutaochu/miniconda3/envs/talk2car/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/lutaochu/miniconda3/envs/talk2car/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ../wemd/lib/libwemd.so: cannot open shared object file: No such file or directory
```
I don't find any doc or code about that in this repo. Can someone help me? It's a bit urgent.

**Comment by ThierryDeruyttere** [comment]
Thanks for raising this issue. I forgot to add this file.
Check https://github.com/ThierryDeruyttere/Talk2Car-Destination/tree/master/baselines/wemd
